# Generated by Django 5.0.4 on 2024-04-08 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-pics')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('matches', models.ManyToManyField(through='user_app.Match', to='user_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='user1_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='user_app.profile'),
        ),
    ]
