# Generated by Django 5.0.4 on 2024-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='recipricated',
            field=models.BooleanField(default=False),
        ),
    ]
