# Generated by Django 5.0.4 on 2024-04-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_match_recipricated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('NB', 'Non-Binary'), ('OT', 'Other'), ('NA', 'N/A')], default='N/A'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.IntegerField()),
                ('male', models.BooleanField()),
                ('female', models.BooleanField()),
                ('non_binary', models.BooleanField()),
                ('other', models.BooleanField()),
                ('n_a', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_preference', to='user_app.profile')),
            ],
        ),
    ]
