# Generated by Django 5.0.4 on 2024-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profile_gender_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='age_range',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='female',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='male',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='n_a',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='non_binary',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='other',
            field=models.BooleanField(null=True),
        ),
    ]
