# Generated by Django 5.0.4 on 2024-04-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_preference_age_range_alter_preference_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='female',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='male',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='n_a',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='non_binary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='other',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
    ]
