# Generated by Django 5.0.4 on 2024-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GamesProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=30)),
                ('gameImage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GamesInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ManyToManyField(to='games_app.games')),
            ],
        ),
        migrations.CreateModel(
            name='GamesPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playAgain', models.BooleanField()),
                ('game', models.ManyToManyField(to='games_app.games')),
            ],
        ),
        migrations.CreateModel(
            name='GamesPlaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('preference', models.CharField(max_length=50)),
                ('game', models.ManyToManyField(to='games_app.games')),
            ],
        ),
    ]
