# Generated by Django 5.0.4 on 2024-04-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0002_remove_gamesinterested_game_remove_gamesplayed_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-pics')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('matches', models.ManyToManyField(through='games_app.Match', to='games_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Played'), ('PG', 'Playing'), ('I', 'Interested')], default='PD', max_length=2)),
                ('ign', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=20)),
                ('competitive', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_app.game')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_app.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='gamesInterested',
        ),
        migrations.RemoveField(
            model_name='games',
            name='gamesPlayed',
        ),
        migrations.RemoveField(
            model_name='games',
            name='gamesPlaying',
        ),
        migrations.DeleteModel(
            name='GamesProvided',
        ),
        migrations.AddField(
            model_name='match',
            name='user1_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='games_app.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='games_app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(through='games_app.UserGame', to='games_app.game'),
        ),
        migrations.DeleteModel(
            name='GamesInterested',
        ),
        migrations.DeleteModel(
            name='GamesPlayed',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='GamesPlaying',
        ),
    ]
