# Generated by Django 5.0.4 on 2024-04-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0002_remove_gamesinterested_game_remove_gamesplayed_game_and_more'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Played'), ('PG', 'Playing'), ('I', 'Interested')], default='PD', max_length=2)),
                ('ign', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=20)),
                ('competitive', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_app.game')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='gamesInterested',
        ),
        migrations.RemoveField(
            model_name='games',
            name='gamesPlayed',
        ),
        migrations.RemoveField(
            model_name='games',
            name='gamesPlaying',
        ),
        migrations.DeleteModel(
            name='GamesProvided',
        ),
        migrations.DeleteModel(
            name='GamesInterested',
        ),
        migrations.DeleteModel(
            name='GamesPlayed',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='GamesPlaying',
        ),
    ]
