# Generated by Django 5.0.4 on 2024-04-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0003_game_usergame_remove_games_gamesinterested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='usergame',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
