# Generated by Django 5.0.4 on 2024-04-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0004_rename_game_id_usergame_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='profile',
            new_name='proile',
        ),
    ]
