# Generated by Django 5.0.4 on 2024-04-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0005_rename_profile_usergame_proile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='usergame',
            old_name='proile',
            new_name='profile_id',
        ),
    ]
